Add Merchant Transaction Support
mmohades/Venmo pull request #53
Opened 2021-07-23 07:29 UTC by babbitt

The following adds support for transactions that occur between a user and a merchant (such as a restaurant). These are common when using a Venmo credit or debit card. 

These changes introduce no breaking changes from what I can tell.

First time contributor to the package so I opted for style consistency over readability in certain cases. Please feel free to offer other solutions. No offense taken in advance.

If these are welcome I'd also be interested in adding bank transfer transaction support.

2021-07-28 03:02 UTC, mmohades requested changes
Thanks for opening this PR! I've been meaning to add other transaction types support for a long time but I've never gotten to do it. I left a comment on doing a refactor in the code, please review that and let me know if you'd want to do it.

2021-07-28 03:04 UTC, mmohades commented
Also, please install pylint to help with some of the style suggestions. https://code.visualstudio.com/docs/python/linting

2021-07-28 03:09 UTC, babbitt commented
Happy to make these changes! Definitely just left this PR in kind of a garbage state as a POC to make sure it would even be of interest. I'll get started on those changes you suggested and see if I can cook up anything else of my own.

2021-08-29 00:11 UTC, mmohades commented
Any updates on this?

2021-08-29 04:54 UTC, babbitt commented
Apologies. Just got back to college so this (as most things) is a bit in flux. You'll see an update from me sometime in the next week or so just getting settled back in here.

2021-12-31 21:17 UTC, mmohades commented
Closing due to inactivity. Please feel free to open a new PR.

2021-12-31 21:17 UTC, closed without merging